// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOkM8DPY-9CZk258-T1D8xGiD7QrNkezk',
    appId: '1:1082554345068:web:53961eca3c5e1d297a9a49',
    messagingSenderId: '1082554345068',
    projectId: 'moralappauth',
    authDomain: 'moralappauth.firebaseapp.com',
    storageBucket: 'moralappauth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNiNqD4Kcd2lgJWABd2T46Oz-UNxjk9iQ',
    appId: '1:1082554345068:android:9ec2f7691c24e6ca7a9a49',
    messagingSenderId: '1082554345068',
    projectId: 'moralappauth',
    storageBucket: 'moralappauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABa8RRGsGchk9Pm81lJIi7JeK_m5emBzg',
    appId: '1:1082554345068:ios:ad7a1daf5e57f50a7a9a49',
    messagingSenderId: '1082554345068',
    projectId: 'moralappauth',
    storageBucket: 'moralappauth.appspot.com',
    iosBundleId: 'com.example.moralApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABa8RRGsGchk9Pm81lJIi7JeK_m5emBzg',
    appId: '1:1082554345068:ios:ad7a1daf5e57f50a7a9a49',
    messagingSenderId: '1082554345068',
    projectId: 'moralappauth',
    storageBucket: 'moralappauth.appspot.com',
    iosBundleId: 'com.example.moralApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOkM8DPY-9CZk258-T1D8xGiD7QrNkezk',
    appId: '1:1082554345068:web:8c8f4ea81989a81c7a9a49',
    messagingSenderId: '1082554345068',
    projectId: 'moralappauth',
    authDomain: 'moralappauth.firebaseapp.com',
    storageBucket: 'moralappauth.appspot.com',
  );
}
